### ISSUE TITLE
Can we use this code for academic research?

### ISSUE THREAD

**Issue by LiuYangMage** [vivienseguy/Large-Scale-OT#2]
Dear Author @vivienseguy 
Thanks so much for posting the code here! We are pretty interested in this method, we want to cite this code/paper, do some comparison in our paper. However, there is no license information in the repository, therefore we cannot use your code by default.
Can we have your permission to use your code, apply to our problem, and show the results on our paper?
Thanks!

**Comment by vivienseguy** [comment]
Hello Liu Yang,
I am glad you are interested in the code! Yes you can use it for your research and plot whatever you want with it. 
Vivien

**Comment by LiuYangMage** [comment]
Hi Vivien:
Thanks so much for your permission!
P.S., it's really a good paper! 
Liu

**Comment by vivienseguy** [comment]
You're welcome. I am looking forward to reading your paper!

**Comment by LiuYangMage** [comment]
@vivienseguy  Just for a confirmation, can we show quantitative results in the paper?
